@admin-jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzI3ODE2Njl9.FF457b5ZcaxIApP2Bud6y3wsxxX7bACumRlI-aepAA0
@user-jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzI3ODEwMzJ9.0RlJh20LCJPzbCUszDNOmqu8qjsW9HTY9115WFQtBs0

### USERS INDEX 

GET http://localhost:3000/users.json


### USERS CREATE (SIGN UP)

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "User",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### USERS UPDATE

{
  "first_name":,
  "last_name":,
  "email":,
  "image_url":,
  "phone":,
  "birth_date":,
  "home_address":,
  "bio":,

}

### SESSIONS CREATE (LOG IN)

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mark@example.com",
  "password": "password"
}

### EVENTS INDEX

GET http://localhost:3000/events.json

### EVENTS CREATE

POST http://localhost:3000/events.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}

{
    "name": "Test Event",
    "description": "Test Text",
    "address": "1234 N Happy Rd, Phoenix, AZ 85251",
    "image_url": "www.google.com" ,
    "start_time": "2023-04-01",
    "end_time": "2023-04-02"
}

### EVENTS UPDATE

PATCH http://localhost:3000/events/3.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}

{
    "name": "Test 2",
    "description": "Test Text",
    "address": "1234 N Happy Rd, Phoenix, AZ 85251",
    "image_url": "www.google.com" ,
    "start_time": "2023-04-01",
    "end_time": "2023-04-02"
}


### EVENTS DESTROY


DELETE http://localhost:3000/events/1.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}