@admin-jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzM0NjEzNjF9.EaGDYZRoqUpwjV-tG99rhzxNqocFTIkHPmd_9VwhF2k
@user-jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NzI4NjIyNjd9.DNI3Cd1YwzB1fgyLTNXFhQ_1TcEOQ5GMdFOrUvAmXC4

### USERS INDEX 

GET http://localhost:3000/users.json


### USERS CREATE (SIGN UP)

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "Amanda",
  "last_name": "HaleNo",
  "email": "amanda@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### USERS UPDATE

{
  "first_name":,
  "last_name":,
  "email":,
  "image_url":,
  "phone":,
  "birth_date":,
  "home_address":,
  "bio":,

}

### SESSIONS CREATE (LOG IN)

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mark@example.com",
  "password": "password"
}

### EVENTS INDEX

GET http://localhost:3000/events.json

### EVENTS CREATE

POST http://localhost:3000/events.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}

{
    "name": "Third TLWO Meeting",
    "description": "Test Text",
    "address": "999 W Sun St., Phoenix, AZ 85251",
    "image_url": "www.google.com" ,
    "start_time": "2023-04-01",
    "end_time": "2023-04-02"
}

### EVENTS UPDATE

PATCH http://localhost:3000/events/12.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}

{
    "start_time": "2023-04-01",
    "end_time": "2023-04-02"
}


### EVENTS DESTROY


DELETE http://localhost:3000/events/13.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}


### FAVORITE INDEX

GET http://localhost:3000/favorites.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}

### FAVORITE CREATE

POST http://localhost:3000/favorites.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}

{
  "event_id": 5
}

### FAVORITE DESTROY

DELETE http://localhost:3000/favorites/6.json
Content-Type: application/json
Authorization: Bearer {{admin-jwt}}

