### USERS INDEX 

GET http://localhost:3000/users.json


### USERS CREATE (SIGN UP)

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "User",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### EVENTS INDEX

GET http://localhost:3000/events.json